### ISSUE TITLE
 starlette.middleware.sessions support?

### ISSUE THREAD

**Issue by cj** [thearchitector/starlette-securecookies#3]
Hi @thearchitector,

Thank you for this awesome lib!

Should this work with starlette.middleware.sessions? I have noticed the cookies are not encrypted:

```python
app = FastAPI()
app.add_middleware(
    SecureCookiesMiddleware,
    secrets=env.cookie_secrets,
    included_cookies=env.cookie_allowed_list,
)
app.add_middleware(SessionMiddleware, secret_key=env.session_secret_key)
```

**Comment by thearchitector** [comment]
thanks for the kind words!

as for SessionMiddleware, it should work fine. I strongly suspect that the reason you're not seeing it work properly is because `.add_middleware` [prepends the middleware to the front of the call stack](https://github.com/encode/starlette/blob/01aa49a379520d3bbe6bc1aecc48a48169e6b004/starlette/applications.py#L137-L140). SecureCookies can only encrypt cookies that are already present in the response (or decrypt those already in the request), so it needs to be added _after_ all other middlewares

**Comment by thearchitector** [comment]
@cj thanks for the kind words!

playing around with it locally, it seems to be working fine for me. i strongly suspect the reason you're not seeing it work is because `.add_middleware` [prepends the middleware to the call stack](https://github.com/encode/starlette/blob/01aa49a379520d3bbe6bc1aecc48a48169e6b004/starlette/applications.py#L137-L140).

so on the request: session is tries to read the cookie => then secure tries to decrypt it  
and on the response: secure encrypts => then session sets a new one

try switching the order of your `.add` calls so the secure middleware does it things after Session

_EDIT_

i added a test for third party middlewares just for posterity as well as updated the docs to make the importance of ordering clear

**Comment by thearchitector** [comment]
didn't mean to close this -- github did it automatically because of the linked issue 🙄

**Comment by cj** [comment]
@thearchitector ha - no problem; thank you for the response! You were correct; with FastAPI, what you declare first is loaded last.
